### ISSUE TITLE
在自定义组件使用时失效及解决思路

### ISSUE THREAD

**Issue by 1057376155** [tomfriwel/weapp-qrcode#1]
在自定义组件使用的时候会失效，因为没有传入this，看官方文档的时候发现
![_20180530184254](https://user-images.githubusercontent.com/18670671/40715804-65704b3e-6439-11e8-890f-4ee876dcb203.png)
建议作者 可以预留 this可传 参数

#### 参考
- [wx.createCanvasContext(canvasId, this)](https://developers.weixin.qq.com/miniprogram/dev/api/canvas/create-canvas-context.html)

**Comment by tomfriwel** [comment]
@1057376155 已解决。

**Comment by xingzhewj** [comment]
如何解决的呢？taro子组件依旧绘制不显示二维码图像。

**Comment by tomfriwel** [comment]
要将`this`传给`usingIn`

**Comment by z1511676208** [comment]
在uni-app里面即使传入子组件this，也没有绘制，为啥呢，想了解一下
