### ISSUE TITLE
支付宝小程序可以使用吗？

### ISSUE THREAD

**Issue by wyhu** [tomfriwel/weapp-qrcode#10]

**Comment by tomfriwel** [comment]
不清楚，你可以试试将里面的`wx.xxxxxx`改成支付宝的API。

**Comment by wyhu** [comment]
试了，不行😂




------------------ 原始邮件 ------------------
发件人: tomfriwel <notifications@github.com>
发送时间: 2019年6月4日 15:46
收件人: tomfriwel/weapp-qrcode <weapp-qrcode@noreply.github.com>
抄送: 胡伟亚 <596031524@qq.com>, Author <author@noreply.github.com>
主题: 回复：[tomfriwel/weapp-qrcode] 支付宝小程序可以使用吗？ (#10)

**Comment by tomfriwel** [comment]
那你看搜搜看有没有其他的相关工具，或者能把这个改写成支付宝的版本。
