### ISSUE TITLE
二维码字符过长，会在最前面产生一个非法字符集，只有在浏览器上才能看见一个小红点

### ISSUE THREAD

**Issue by wanngzelin** [tomfriwel/weapp-qrcode#13]
二维码字符过长，会在最前面产生一个非法字符集，只有在浏览器上才能看见一个小红点

**Comment by tomfriwel** [comment]
有测试数据吗？我试试看

**Comment by wanngzelin** [comment]
"﻿{"userId":"7b402a95-00e6-4fca-a1d8-96e591fdfd90",…111111111111111111111111111111111111111111":"王林"}", scanType: "QR_CODE", charSet: "UTF-8", rawData: "77u/eyJ1c2VySWQiOiI3YjQwMmE5NS0wMGU2LTRmY2EtYTFkOC…xMTExMTExMTExMTExMTExMTExMTExMTExIjoi546L5p6XIn0="}             把前面那段字符放在控制台，就能在最前面看见一个非法字符集  小红点

**Comment by tomfriwel** [comment]
控制台显示出来的东西应该跟我这个组件没什么关系吧，是可以看看你的字符串里面是不是有什么特殊字符串。
