### ISSUE TITLE
小程序生成的二维码有时会出现白色小块在二维码上，导致二维码显示不正确

### ISSUE THREAD

**Issue by zxzhgk** [tomfriwel/weapp-qrcode#3]
QRCode.CorrectLevel.L

QRCode.CorrectLevel.M

QRCode.CorrectLevel.Q

QRCode.CorrectLevel.H
这几个级别都试了，大概40%左右的概率会出现

**Comment by zxzhgk** [comment]
目前好像是安卓手机有这个问题，苹果的正常

**Comment by tomfriwel** [comment]
> 目前好像是安卓手机有这个问题，苹果的正常

有截图吗

**Comment by tomfriwel** [comment]
@zxzhgk 有截图吗？

**Comment by zxzhgk** [comment]
当时忘记忘记截图了，就是会出现很多正方形的白色小块。我目前换了一个生成的库就好了

**Comment by zxzhgk** [comment]
我是用安卓的小米手机测试的，也有可能只是小米会这样

**Comment by Albuseven** [comment]
> 当时忘记忘记截图了，就是会出现很多正方形的白色小块。我目前换了一个生成的库就好了

请问你换的是啥库，我也有这个问题
